apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./.infra/k8s/*
      - ./.infra/k8s-dev/*
build:
  local:
    push: false # do not push Dockerfile to cluster
  artifacts:
    - image: briceth/auth
      context: auth
      docker:
        dockerfile: .docker/dev/Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: briceth/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
    - image: briceth/tickets
      context: tickets
      docker:
        dockerfile: .docker/dev/Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: briceth/orders
      context: orders
      docker:
        dockerfile: .docker/dev/Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: briceth/expiration
      context: expiration
      docker:
        dockerfile: .docker/dev/Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: briceth/payments
      context: payments
      docker:
        dockerfile: .docker/dev/Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
