apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-mongo-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets-mongo
  template:
    metadata:
      labels:
        app: tickets-mongo
    spec:
      containers:
        - name: tickets-mongo
          image: mongo
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: 'admin'
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: 'password'
            - name: MONGO_INITDB_DATABASE
              value: tickets
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: tickets-mongo-srv
spec:
  selector:
    app: tickets-mongo
  ports:
    - name: tickets-mongo-srv
      protocol: TCP
      port: 27017
      targetPort: 27017
