name: deploy-payments

on:
  push:
    branches:
      - main
    paths:
      - payments/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build container image
        run: cd payments && docker build -t briceth/payments .
      - name: Log in to docker hub
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push image to docker
        run: docker push briceth/payments
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Save & switch DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save ticketing
      - name: Restart deployment and use last image from docker hub
        run: kubectl rollout restart deployment payments-depl
