name: deploy-manifests

on:
  push:
    branches: main
    paths: infra/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Save & switch DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save ticketing
      - name: Apply k8s manifests to cluster
        run: kubectl apply -f infra/k8s
